import type { Metadata } from "next"

import { LegalDocumentPage } from "@/components/legal/LegalDocumentPage"

export const metadata: Metadata = {
  title: "Privacy Policy | Clairvyn",
  description: "Privacy Policy for Clairvyn Private Limited",
}

const policyBody = `Reference source:
CLAIRVYN PRIVATE LIMITED
Privacy Policy
Governing the collection, processing, storage, and disclosure of personal data by Clairvyn Private Limited
Effective Date: 14 March 2026

Company	Clairvyn Private Limited
CIN	U62099TN2025PTC180011
GSTIN	33AAMCC6875A1ZO
Registered Address	No.136/1, No.8/9, Parvallal Street, Murugappa Nagar, Ennore RS, Ambattur, Tiruvallur – 600057, Tamil Nadu, India
Contact	hello@clairvyn.com
Website	www.clairvyn.com
Effective Date	14 March 2026




1. Preliminary
This Privacy Policy ("Policy") is published by Clairvyn Private Limited, a company incorporated under the Companies Act, 2013, having its registered office at No.136/1, No.8/9, Parvallal Street, Murugappa Nagar, Ennore RS, Ambattur, Tiruvallur – 600057, Tamil Nadu, India, bearing Corporate Identification Number U62099TN2025PTC180011 and GSTIN 33AAMCC6875A1ZO ("Clairvyn", "Company", "we", "us", or "our"). This Policy governs the collection, processing, storage, transfer, and disclosure of personal data submitted to or generated through the Company's AI-powered architectural floor plan generation platform, accessible at www.clairvyn.com, together with all associated applications, application programming interfaces, tools, and services (collectively, the "Platform"). This Policy is published in compliance with the Digital Personal Data Protection Act, 2023 ("DPDPA"), the Digital Personal Data Protection Rules, 2025 ("DPDP Rules"), the Information Technology Act, 2000 and rules thereunder, and, where applicable, the General Data Protection Regulation (EU) 2016/679 ("GDPR") and other applicable data protection laws.
By accessing or using the Platform in any manner, you, as the Data Principal or data subject, acknowledge that you have read, understood, and consent to the terms of this Policy. If you do not agree with any provision of this Policy, you must immediately discontinue use of the Platform. This Policy is incorporated into and forms an integral part of the Terms of Service governing your use of the Platform.

2. Scope and Applicability
This Policy applies to all natural persons who access or use the Platform, including visitors to the Company's website, registered users, free-tier users, paid subscribers, collaborators invited by registered users, and non-registered individuals who access view-only shared outputs via public links (collectively, "Users"). The Policy applies regardless of the User's geographic location. Specific provisions applicable to Users located in the European Economic Area ("EEA") are set out in Section 14 of this Policy.
This Policy does not govern the data practices of third-party websites, services, or applications that may be linked from the Platform. The Company accepts no responsibility for the privacy practices of such third parties.

3. Personal Data Collected
3.1 Data Provided Directly by Users
The Company collects the following categories of personal data that Users provide directly: (a) identity data, comprising the User's full name and email address, collected at the time of account registration; (b) authentication credentials, comprising the User's chosen password, which is stored exclusively in hashed and salted form using bcrypt or Argon2id cryptographic hashing — the Company does not store passwords in plaintext or in any reversibly encrypted form under any circumstances; (c) floor plan inputs and design briefs, comprising the textual prompts, spatial parameters, dimensional requirements, room configurations, and design preferences submitted by the User through the Platform's generation interface; (d) project and collaboration data, comprising project titles, collaborator identities and access permissions, version history of shared floor plans, and activity logs generated in the course of using the Platform's collaboration features; (e) communications data, comprising the content of correspondence submitted by the User through the Platform's support interface, feedback mechanisms, or direct email communication with the Company; and (f) payment and billing data, comprising the User's billing name, billing address, and payment method details submitted in connection with a paid subscription, which are processed exclusively by the Company's authorised third-party payment processor — the Company does not store full payment card numbers, card verification values, or equivalent sensitive payment credentials on its own systems.

3.2 Data Generated Through Use of the Platform
The Company collects the following categories of data generated through a User's interaction with the Platform: (a) generated outputs, comprising the architectural floor plans, design layouts, and spatial configurations produced by the Platform's AI models in response to User inputs; (b) usage and behavioural data, comprising features accessed, prompts submitted, iterations generated, session duration, navigation patterns, click events, and in-application interaction data, collected through analytics tools integrated into the Platform; and (c) subscription and transaction history, comprising the User's plan tier, subscription commencement and renewal dates, upgrade and downgrade events, and billing transaction records.

3.3 Data Collected Automatically
The Company automatically collects the following technical data from all Users, including non-registered individuals who access the Platform via shared links: (a) device and technical data, comprising IP address, browser type and version, operating system and version, device type, screen resolution, and language and locale settings; (b) server log data, comprising access logs, error logs, request metadata, and timestamps of all interactions with the Platform's infrastructure; and (c) cookie and tracking data, as described in Section 11 of this Policy.
With respect to non-registered individuals who access a floor plan output shared via a public view-only link, the Company collects device and technical data and server log data solely for the purposes of security monitoring, fraud prevention, and abuse detection. No persistent user profile is created for such individuals and no personal data so collected is used for any commercial purpose other than the security and integrity of the Platform.

3.4 Data the Company Does Not Collect
The Company does not intentionally collect sensitive personal data as defined under the DPDPA, including but not limited to government-issued identification numbers, biometric data, health and medical information, financial account numbers beyond what is strictly required for payment processing, data concerning racial or ethnic origin, religious or political beliefs, or sexual orientation. In the event that a User inadvertently embeds such information within a floor plan prompt or other input, that data is subject to the prompt sanitisation process described in Section 9 of this Policy and is not retained in identifiable form beyond what is operationally necessary.

4. Purposes of Processing
The Company processes personal data collected through the Platform for the following specific and lawful purposes: (a) to create and maintain User accounts and to authenticate Users accessing the Platform; (b) to receive, process, and transmit the User's floor plan inputs to the applicable AI model provider and to return the generated output to the User; (c) to enable project collaboration features, including synchronising project data between authorised collaborators, managing access permissions, and maintaining version history of shared floor plans; (d) to process subscription payments and to manage the User's billing relationship with the Company; (e) to analyse usage behaviour and product performance for the purpose of improving the Platform's features, models, and user experience; (f) to send transactional communications, including account verification emails, password reset notifications, billing confirmations, and service-critical notices, which are transmitted irrespective of the User's marketing communication preferences; (g) to send marketing communications, including product updates, feature announcements, and promotional information, subject to the User's consent and the User's right to opt out at any time; (h) to prepare, compile, and share anonymised and aggregated datasets derived from User data with authorised data partners, in accordance with the anonymisation standard and safeguards set out in Section 9 of this Policy; (i) to detect, investigate, and prevent fraudulent activity, security incidents, and misuse of the Platform; (j) to exercise and defend the Company's legal rights and to comply with applicable laws, regulations, court orders, and lawful requests from regulatory authorities; and (k) to fulfil any other purpose for which the User provides express consent at the time of data collection.

5. Legal Bases for Processing
5.1 Under the Digital Personal Data Protection Act, 2023
The Company processes personal data on the following legal bases under the DPDPA: (a) consent of the Data Principal, obtained through an explicit, affirmative, and informed consent mechanism presented prior to the collection of any personal data, as described in the standalone Consent Notice published by the Company in accordance with Section 5 of the DPDPA; and (b) certain legitimate uses as provided under the DPDPA and DPDP Rules, including processing reasonably necessary for the provision of services requested by the Data Principal, for the prevention and detection of fraud, and for compliance with legal obligations binding on the Company.

5.2 Under the General Data Protection Regulation (EU Users)
For Users located in the EEA, the Company relies on the following legal bases under the GDPR: (a) performance of a contract pursuant to Article 6(1)(b), for processing necessary to provide the Platform services requested by the User; (b) legitimate interests pursuant to Article 6(1)(f), for processing undertaken for analytics, security monitoring, fraud prevention, and product improvement, where the Company's legitimate interests are not overridden by the User's fundamental rights and freedoms; (c) consent pursuant to Article 6(1)(a), for marketing communications and for non-essential cookies; and (d) compliance with a legal obligation pursuant to Article 6(1)(c), where processing is required by applicable law.

6. Third-Party Data Processors
The Company engages the following categories of third-party service providers as data processors, each of whom processes personal data exclusively on the Company's behalf and under binding data processing agreements that impose obligations of confidentiality, security, and compliance consistent with applicable data protection law: (a) cloud infrastructure providers, comprising Amazon Web Services and Google Cloud Platform, for the hosting, storage, and computation infrastructure underlying the Platform — User data may be stored in data centres located in India and/or in other jurisdictions operated by these providers; (b) AI model providers, comprising Google Gemini API and such other third-party or self-hosted open-source AI model providers as the Company may engage from time to time, for the processing of floor plan prompts and the generation of outputs — the Company reviews and confirms, prior to engaging any AI model provider, that API inputs are not retained by the provider for the purpose of training the provider's own models; (c) payment processors, comprising such authorised third-party payment processors as the Company engages from time to time, for the processing of subscription payments — the identity of the active payment processor is disclosed on the payment interface within the Platform at the point of transaction; (d) analytics providers, for the collection and analysis of usage and behavioural data for product improvement purposes; and (e) collaboration and cloud storage infrastructure providers, for the storage, synchronisation, and management of shared project data.
The Company does not sell, rent, trade, or otherwise transfer personal data to any third party for that party's independent marketing, commercial, or advertising purposes. Any disclosure of data to third parties is limited to the processor relationships described in this Section and the data partnership arrangements described in Section 9.

7. Cross-Border Data Transfers
The Company is incorporated and operates in India. User personal data may be transferred to and processed in jurisdictions outside India, including the United States, in connection with the cloud infrastructure, AI model, and analytics processing described in Section 6. All cross-border transfers of personal data are subject to appropriate safeguards. For transfers to jurisdictions that are designated as trusted geographies by the Government of India under the DPDPA, the Company relies on that designation as the applicable transfer mechanism. For transfers to other jurisdictions, the Company relies on contractual safeguards, including data processing agreements with processors that incorporate provisions consistent with applicable cross-border transfer requirements. For transfers of personal data originating in the EEA to India or the United States, the Company relies on Standard Contractual Clauses approved by the European Commission as the applicable transfer mechanism under the GDPR. Anonymised and aggregated data shared with data partners under Section 9 is not personal data and is not subject to cross-border transfer restrictions; however, the Company discloses that such data may be transferred to and used by partners located outside India, including in the United States and Europe.

8. Data Retention
The Company retains personal data only for as long as necessary to fulfil the purpose for which it was collected or as required by applicable law. The following retention periods govern the Company's data management practices: identity data and account information are retained for the duration of the User's account and for a period of three years following account closure, for the purpose of legal compliance and dispute resolution; floor plan inputs and generated outputs are retained for the duration of the User's account and are subject to deletion upon the User's request as described in Section 12; usage and behavioural data collected through analytics tools is retained in identifiable or pseudonymised form for a period of twenty-four months, following which it is irreversibly aggregated or deleted; payment records and transaction data are retained for a minimum period of seven years in compliance with applicable tax, accounting, and financial record-keeping laws; communications and support correspondence are retained for three years from the date of the last interaction; and technical and server log data is retained for twelve months for security and fraud prevention purposes. Upon account deletion, the Company will delete or irreversibly anonymise the User's personal data within thirty days, subject to any retention obligations imposed by law.

9. Data Partnerships and Anonymisation
9.1 Nature of Data Partnerships
The Company enters into data partnership arrangements with companies and institutions in the architecture, construction, technology, and research sectors, under which the Company shares derived datasets for purposes including industry research, AI model development, design trend analysis, and related commercial applications. Such partnerships may involve the receipt of monetary or non-monetary consideration by the Company. The Company does not sell personal data. All data shared under these arrangements is subject to the anonymisation standard set out in Section 9.2 and the contractual safeguards set out in Section 9.3. Data partners may be located in India or in jurisdictions outside India, including the United States and Europe.

9.2 Anonymisation Standard
Prior to sharing any data with a data partner, the Company applies the following four-tier anonymisation standard: (a) Tier 1 — Direct Identifier Removal: all direct personal identifiers, including name, email address, user account identifier, IP address, device fingerprint, and any other field capable of directly identifying a natural person, are stripped from the dataset. Where a record-level identifier is required for the partner's analytical purposes, the Company substitutes a one-way hashed pseudonym generated using a salt that is retained exclusively by the Company and is never disclosed to any partner; (b) Tier 2 — Prompt Sanitisation: all floor plan prompt text included in a dataset is processed through the Company's prompt sanitisation pipeline prior to sharing. The pipeline detects and removes personally identifiable content that may be embedded within prompts by Users, including but not limited to property addresses, client names, contact numbers, plot registration numbers, and location-specific identifiers. Any prompt record that fails sanitisation is excluded from the dataset in its entirety; (c) Tier 3 — Parameter Generalisation: numerical and categorical parameters, including plot dimensions, room counts, floor counts, and design configuration values, are generalised into discrete ranges or categories prior to sharing at the row level, such that no individual record reflects a precise value capable of identifying a specific property or project; and (d) Tier 4 — Minimum Group Size for Aggregated Statistics: no statistical or aggregated output derived from User data is shared with any partner if it is derived from fewer than fifty individual records, so as to prevent inference of individual behaviour or characteristics from small-cohort data.

9.3 Partner Contractual Safeguards
The Company enters into written data partnership agreements with all data partners prior to any transfer of data. Such agreements require the partner to: use the data exclusively for the purposes specified in the agreement; maintain appropriate technical and organisational security measures; refrain from any attempt to re-identify individuals from the anonymised data; refrain from combining the anonymised data with other datasets in a manner that could result in re-identification; and promptly notify the Company of any breach or suspected breach of these obligations. The Company conducts due diligence on the anonymisation practices and security posture of prospective data partners prior to entering into any partnership.

9.4 User Opt-Out Rights
Users have the right to opt out of the inclusion of their data in row-level anonymised datasets shared with data partners. This opt-out right applies to record-level data sharing and may be exercised at any time by contacting the Company at the address set out in Section 15. The opt-out right does not extend to aggregated statistical outputs, which by their nature do not reflect individual User data and to which no individual opt-out right applies. Exercise of the opt-out right does not affect the User's ability to use the Platform.

10. Data Security
The Company implements appropriate technical and organisational measures to protect personal data against unauthorised access, disclosure, alteration, loss, and destruction. These measures include encryption of data in transit using Transport Layer Security protocols, hashing of passwords and authentication credentials using cryptographic algorithms as described in Section 3.1, role-based access controls restricting access to personal data to authorised personnel on a need-to-know basis, and regular security reviews of the Company's infrastructure and third-party processors. In the event of a personal data breach that is likely to result in harm to Data Principals, the Company will notify the Data Protection Board of India within seventy-two hours of becoming aware of the breach and will notify affected Users without undue delay, describing the nature of the breach, the categories and approximate volume of data involved, the likely consequences, and the measures taken or proposed by the Company. No system of data security is infallible. The User is responsible for maintaining the confidentiality of their account credentials and for notifying the Company immediately of any suspected unauthorised access to their account.

11. Cookies and Tracking Technologies
The Platform uses cookies and similar tracking technologies. Cookies are small data files placed on the User's device that enable the Platform to function correctly and to collect usage data. The Company uses the following categories of cookies: strictly necessary cookies, which are essential to the operation of the Platform and cannot be disabled, including session authentication tokens and security cookies; analytics cookies, which collect anonymised usage data to enable the Company to understand how Users interact with the Platform, and which are placed only with the User's explicit consent; and preference cookies, which store the User's settings and configuration preferences. On the User's first visit to the Platform, the Company presents a cookie consent interface that allows the User to accept or decline non-essential cookies. The User may update their cookie preferences at any time through the cookie settings accessible from the Platform's footer. Declining analytics cookies does not impair the core functionality of the Platform.

12. Rights of Data Principals and Data Subjects
12.1 Rights Under the DPDPA
Every Data Principal whose personal data is processed by the Company has the following rights under the DPDPA, which may be exercised by contacting the Grievance Officer at the details set out in Section 13: (a) the right to obtain confirmation of whether the Company processes personal data relating to them, and to obtain a summary of such data and the processing activities carried out thereon; (b) the right to request correction of inaccurate personal data and completion of incomplete personal data; (c) the right to request erasure of personal data in circumstances permitted under the DPDPA, including upon withdrawal of consent; (d) the right to withdraw consent to processing at any time, which withdrawal is prospective in effect and does not affect the lawfulness of processing carried out prior to withdrawal, and which may affect the User's ability to access certain features of the Platform; (e) the right to nominate another individual to exercise these rights on behalf of the Data Principal in the event of the Data Principal's death or incapacity; and (f) the right to raise a grievance with the Grievance Officer and to escalate unresolved grievances to the Data Protection Board of India.

12.2 Additional Rights for EEA Users Under the GDPR
Users located in the EEA have the following additional rights under the GDPR: (a) the right to receive a copy of personal data in a structured, commonly used, and machine-readable format, and to transmit that data to another controller, where processing is based on consent or contract and is carried out by automated means; (b) the right to restrict processing in circumstances provided under Article 18 of the GDPR; (c) the right to object to processing based on legitimate interests, including profiling; and (d) the right to lodge a complaint with the data protection supervisory authority of the EEA Member State in which the User habitually resides, works, or where the alleged infringement occurred.

12.3 Response Timelines
The Company will acknowledge all rights requests within forty-eight hours of receipt and will respond substantively within thirty days. Where a request is complex or numerous, the Company may extend the response period by a further thirty days upon notice to the Data Principal. Identity verification will be required before personal data is disclosed or deleted. All rights requests and their disposition are logged and maintained by the Grievance Officer.

13. Grievance Officer
In accordance with Section 13 of the DPDPA and Rule 4 of the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021, the Company has designated the following individual as Grievance Officer for the purposes of receiving and redressing complaints relating to the processing of personal data:

Name	Ronak Marlecha
Designation	Co-Founder and Chief Financial Officer
Organisation	Clairvyn Private Limited
Email	hello@clairvyn.com
Address	No.136/1, No.8/9, Parvallal Street, Murugappa Nagar, Ennore RS, Ambattur, Tiruvallur – 600057, Tamil Nadu, India

Grievances may be submitted in writing to the Grievance Officer at the email address above. The Company will acknowledge receipt within forty-eight hours and will endeavour to resolve the grievance within thirty days of receipt. Users who remain unsatisfied following the Company's response may escalate their complaint to the Data Protection Board of India.

14. Additional Provisions for EEA Users
The Company does not maintain a physical establishment in the EEA. Users accessing the Platform from the EEA should be aware of the following: (a) the Company is the data controller within the meaning of Article 4(7) of the GDPR for all personal data processed through the Platform; (b) the Company is in the process of appointing an EU representative within the meaning of Article 27 of the GDPR, the details of whom will be published in this Policy upon appointment; pending such appointment, EEA Users may direct all GDPR-related enquiries to hello@clairvyn.com; (c) transfers of personal data from the EEA to India and the United States are made under Standard Contractual Clauses as described in Section 7; and (d) EEA Users have the right to lodge a complaint with the competent supervisory authority in their Member State.

15. Children and Minors
The Platform is not directed at children under the age of thirteen years. The Company does not knowingly collect personal data from individuals below the age of thirteen. Users between the ages of thirteen and eighteen must obtain the prior consent of a parent or legal guardian before registering on the Platform. In the event that the Company discovers it has collected personal data from a child below the age of thirteen without verified parental consent, the Company will take immediate steps to delete such data. Parents or guardians who believe their child has provided personal data to the Company without consent should contact the Grievance Officer at the details in Section 13.

16. Amendments to This Policy
The Company reserves the right to amend this Policy at any time to reflect changes in its data practices, changes in applicable law, or changes to the Platform's features. Material amendments will be communicated to registered Users by email to their registered address and by a prominent notice on the Platform not less than seven days prior to the effective date of the amendment. The amended Policy will carry a revised effective date. Continued use of the Platform after the effective date of any amendment constitutes the User's acceptance of the revised Policy. Users who do not accept a material amendment may terminate their account and request erasure of their data as provided in Section 12.

17. Governing Law
This Policy is governed by and construed in accordance with the laws of India. Any dispute arising out of or in connection with this Policy shall be subject to the exclusive jurisdiction of the courts at Chennai, Tamil Nadu, India.

18. Contact
For all enquiries relating to this Policy or the Company's data practices, please contact:

Email	hello@clairvyn.com
Phone	+91 95917 37791
Website	www.clairvyn.com
Address	No.136/1, No.8/9, Parvallal Street, Murugappa Nagar, Ennore RS, Ambattur, Tiruvallur – 600057, Tamil Nadu, India
`

export default function PrivacyPolicyPage() {
  return (
    <LegalDocumentPage
      title="Privacy Policy"
      effectiveDate="Effective Date: 14 March 2026"
      body={policyBody}
    />
  )
}
